# Generated by Django 3.2.6 on 2021-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/img')),
                ('description', models.CharField(max_length=50)),
                ('twitter_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('telegram_url', models.CharField(max_length=100)),
            ],
        ),
    ]
