# Generated by Django 3.2.6 on 2021-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_managerslist_telegram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/img')),
                ('description', models.CharField(max_length=50)),
                ('twitter_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
            ],
        ),
    ]
